### ISSUE TITLE
add python3 build

### ISSUE THREAD

**Issue by ltalirz** [aiidalab/aiidalab-metapkg#14]
@yakutovicha 

just to mention what the [`develop-py3`](https://github.com/aiidalab/aiidalab-metapkg/commit/cf3b68ab3441ec4c53f376bdae5889e90a6c4224) branch was about:

When you run pipenv on python3, you will get different dependencies (e.g. lots of the dependencies you get for python2.7 are backports of python3 functionality).

When I created the develop-py3 branch, the Pipfile approach was broken, so I updated the requirements.txt by hand. If I understand correctly, it is working again now, correct?

If yes, then perhaps it would make sense to create a `requirements3.txt` which is the result of the same command run under python3.

We would then need to release a wheel for py2 and one for py3...
not so urgent perhaps, since it seems that travis currently checks installing under python 3.7 and it seems to work fine
https://github.com/aiidalab/aiidalab-https://github.com/aiidalab/aiidalab-metapkg/blob/e7bd3c3b7085145c4b62347c43f4d7cf9b8590c6/.travis.yml#L2-L3

**Comment by yakutovicha** [comment]
The python2 support is kind of dropped already for aiida-1 compatible aiidalab, so I think it is not really needed to move dependencies to the `requirements3.txt` file.

> When I created the develop-py3 branch, the Pipfile approach was broken, so I updated the requirements.txt by hand. If I understand correctly, it is working again now, correct?

there is still some "hand work" involved, but it is describedin the updated `README.txt`. The main difference is that I separated packages with clashing dependencies into `dev-packages` and `packages`. See [the readme](https://github.com/aiidalab/aiidalab-metapkg/blob/master/README.md#updating-requirements) for more details.

**Comment by ltalirz** [comment]
> The python2 support is kind of dropped already for aiida-1 compatible aiidalab, so I think it is not really needed to move dependencies to the requirements3.txt file.

Hm... I thought the dependencies **are** computed for python 2.7, no?
https://github.com/aiidalab/aiidalab-metapkg/blob/e7bd3c3b7085145c4b62347c43f4d7cf9b8590c6/Pipfile#L40-L41

> there is still some "hand work" involved, but it is describedin the updated README.txt. The main difference is that I separated packages with clashing dependencies into dev-packages and packages. See the readme for more details.

Thanks, that looks very sensible.

**Comment by yakutovicha** [comment]
> > The python2 support is kind of dropped already for aiida-1 compatible aiidalab, so I think it is not really needed to move dependencies to the requirements3.txt file.
> 
> Hm... I thought the dependencies **are** computed for python 2.7, no?

and tested for python 3.7...
https://github.com/aiidalab/aiidalab-metapkg/blob/e7bd3c3b7085145c4b62347c43f4d7cf9b8590c6/.travis.yml#L3

I overlooked this, thanks for pointing it out. For the next release I will change python version to 3.7.

**Comment by ltalirz** [comment]
> For the next release I will change python version to 3.7.

I wonder whether this is the right thing to do...
Apparently now we are in a stage, where the dependencies are computed for 2.7 and work both in 2.7 (hopefully?) and in 3.7.
This is essentially what we want.

I'll add a 2.7 build for travis just to be sure.

**Comment by yakutovicha** [comment]
I think this will fail, but you can try. Please do it in a separate branch

**Comment by ltalirz** [comment]
Indeed - ASE dropped python2 support:
https://travis-ci.org/aiidalab/aiidalab-metapkg/jobs/578577540#L246

So, are we no longer supporting python2.7 for AiiDA lab?
... I guess I'm ok with this.

**Comment by ltalirz** [comment]
and we already mention it
https://github.com/aiidalab/aiidalab-metapkg/blob/e7bd3c3b7085145c4b62347c43f4d7cf9b8590c6/setup.json#L11

**Comment by yakutovicha** [comment]
We decided not to support python 2 for aiida-docker-stack/base for 1.0, so should we do for the aiidulab-docker-stack if we want to base it on them.

It does not make much sense indeed since we are typically working inside the docker containers.
